### PR TITLE
Convert hash to a Javascript object so it works with classnames 2.3.0

### LINKED ISSUE #6: New installations of this addon use classnames 2.3.0 which breaks apps in production
### Issue
As of yesterday, when this addon is installed and used with the latest versions of ember, websites crash in production with the error: 

```
Uncaught TypeError: arg.toString is not a function
    at classNames (index.js:39)
    at classNames (class-names.js:10)
    at index.js:3961
    at deprecateMutationsInTrackingTransaction (validator.js:180)
    at index.js:3960
    at SimpleClassicHelperManager.getValue (index.js:3971)
    at manager.js:949
    at reference.js:161
    at track (validator.js:820)
    at valueForRef (reference.js:160)
```

The addon resolves `classnames` to version 2.3.0 which tries to call the `toString` method on the `hash` argument, which doesn't exist.

https://github.com/JedWatson/classnames/blob/f2379c3d1eae8c9d6527279bc6a0630a2e78b051/index.js#L39

### Quick reproduction
basically just `ember new` and `ember install ember-class-names-helper` + simple changes to the application template:

https://github.com/Aierie/classnames-error-reproduction

### PR DESCRIPTION
**Pull request by Aierie**
This lets the addon work for classnames 2.3.0 (fixes #6).

### CODE REVIEW

File: addon/helpers/class-names.js [hunk 1]
```diff
@@ -2,5 +2,9 @@ import { helper } from '@ember/component/helper';
 import classnames from 'classnames';
 
 export default helper(function classNames(params, hash) {
```
Comment (jherdman) [inline addon/helpers/class-names.js:4]: Perhaps we ought to rename the second param to `proxy` to more clearly communicate what it is

File: addon/helpers/class-names.js [hunk 2]
```diff
@@ -2,5 +2,9 @@ import { helper } from '@ember/component/helper';
...
-  return classnames(...params, hash);
+  const hashAsObject = {};
+  for (const key in hash) {
```
Comment (jherdman) [inline addon/helpers/class-names.js:6]: Since `for ... in` enumerates over prototype methods too ought the solution be...

```javascript
const entries = Object.entries(hash);
const hash = Object.fromEntries(entries);

return classnames(...params, hash);
```

**Review by jherdman — CHANGES_REQUESTED** [review]
Thank you for the excellent error report, it made verifying this bug trivial. I'm sorry we didn't catch it sooner! It looks like Github disabled our automated CI on it. Yay...

I left a few notes above. Let me know what you think.

**Comment by Aierie** [comment]
I think `Object.entries` seems nice! re: making people aware of the argument types, added JSdoc to explain the function since both arguments are Glimmer proxies which probably are a bit different from conventional Javascript proxies.

**Review by jherdman — APPROVED** [review]

**Comment by jherdman** [comment]
Many thanks for your contribution! I'll aim to get a release out shortly.
